import React, { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';

export default function AssessmentManager(){
  const [title,setTitle]=useState(''); const [duration,setDuration]=useState(30); const [category,setCategory]=useState(''); const [selected,nullState]=useState(null);
  const [created,setCreated]=useState(null); const [qText,setQText]=useState(''); const [qSkill,setQSkill]=useState(''); const [qPosition,setQPosition]=useState(0); const [optText,setOptText]=useState(''); const [optCorrect,setOptCorrect]=useState(false);
  const create = async ()=>{ const r=await fetch('/api/assessments', { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${localStorage.getItem('sb_token')}` }, body: JSON.stringify({ title, category, duration_minutes: duration }) }); const d=await r.json(); if(r.ok){ setCreated(d); alert('Assessment created'); } else alert(d.error||'Failed'); };
  const addQuestion = async ()=>{ if(!created) return alert('Create assessment first'); const r=await fetch('/api/assessments/'+created.id+'/questions', { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${localStorage.getItem('sb_token')}` }, body: JSON.stringify({ text:qText, position:qPosition, skill_id:qSkill||null }) }); const d=await r.json(); if(r.ok) alert('Question added'); else alert(d.error||'Failed'); };
  const addOption = async (qid)=>{ const r=await fetch('/api/assessments/questions/'+qid+'/options', { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${localStorage.getItem('sb_token')}` }, body: JSON.stringify({ text:optText, is_correct:optCorrect }) }); const d=await r.json(); if(r.ok) alert('Option added'); else alert(d.error||'Failed'); };
  return <div><PageHeader eyebrow="Assessments" title="Assessment manager" description="Create assessments, questions and options." /><div className="panel form-grid"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Duration minutes<input type="number" value={duration} onChange={e=>setDuration(e.target.value)}/></label><div className="form-actions"><Button onClick={create}>Create assessment</Button></div></div><div className="panel form-grid"><h3>Add question</h3><label>Question<textarea value={qText} onChange={e=>setQText(e.target.value)}/></label><label>Skill ID<input value={qSkill} onChange={e=>setQSkill(e.target.value)}/></label><label>Position<input type="number" value={qPosition} onChange={e=>setQPosition(e.target.value)}/></label><div className="form-actions"><Button onClick={addQuestion}>Add question</Button></div></div><div className="panel form-grid"><h3>Add option</h3><label>Question ID<input/></label><label>Option text<input value={optText} onChange={e=>setOptText(e.target.value)}/></label><label><label><input type="checkbox" checked={optCorrect} onChange={e=>setOptCorrect(e.target.checked)}/> Correct</label></label><div className="form-actions"><Button onClick={()=>alert('Use question ID and click Add option')}>Add option</Button></div></div></div>;
}
