import React, { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import Badge from '../components/Badge';
import { useAuth } from '../auth/AuthProvider';
import { supabase } from '../lib/supabaseClient';
import { readableSupabaseError } from '../lib/supabaseData';

export default function CareerGuidance({go}){
  const { user } = useAuth();
  const [tab,setTab]=useState('recommended'); const [careers,setCareers]=useState([]); const [recommendations,setRecommendations]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(null);
  useEffect(()=>{(async()=>{if(!user)return; const [{data:careerData,error:careerError},{data:recommendationData,error:recommendationError}]=await Promise.all([supabase.from('careers').select('id,title,description,industry,career_categories(name),career_skills(skill_id,importance,skills(id,name))').eq('active',true).order('title'),supabase.from('career_recommendations').select('id,career_id,match_score,reasons,matched_skills,missing_skills,careers(id,title,industry,career_skills(skill_id,skills(id,name)))').eq('user_id',user.id).order('match_score',{ascending:false})]); const queryError=careerError||recommendationError;if(queryError)setError(readableSupabaseError(queryError,'Unable to load career guidance.'));else{setCareers(careerData||[]);setRecommendations(recommendationData||[]);}setLoading(false);})();},[user]);
  const recommendationByCareer=new Map(recommendations.map(item=>[item.career_id,item])); const source=tab==='all'?careers:tab==='recommended'?recommendations.map(item=>item.careers).filter(Boolean):careers.filter(c=>recommendationByCareer.has(c.id));
  return <div><PageHeader eyebrow="Career guidance" title="Discover careers that fit you" description="Explore careers using your profile, skills, interests and stored recommendation results."/><div className="tabs"><button className={tab==='recommended'?'active':''} onClick={()=>setTab('recommended')}>Recommended Careers</button><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Explore All</button><button className={tab==='interests'?'active':''} onClick={()=>setTab('interests')}>My Interests</button></div>{error&&<div className="panel error">{error}</div>}{loading?<div className="panel">Loading career guidance…</div>:<div className="career-layout"><div className="panel career-results">{source.length?source.map(c=>{const recommendation=recommendationByCareer.get(c.id);const score=recommendation?.match_score||0;const skills=(c.career_skills||[]).slice(0,4);return <div className="career-card" key={c.id}><div className="mini-icon blue">✦</div><div className="career-card-main"><div><h3>{c.title}</h3><p>{c.industry||c.career_categories?.name||'Career'}</p></div><strong>{score?`${Number(score).toFixed(0)}%`:'—'} <span>match</span></strong><div className="matchbar"><i style={{width:`${score}%`}}></i></div><div className="tags">{skills.map(item=><span key={item.skill_id}>{item.skills?.name}</span>)}</div><button onClick={()=>go&&go('career-'+c.id)}>View career details →</button></div></div>}):<div className="empty">{tab==='recommended'?'No stored AI recommendations yet. Generate recommendations through the recommendation service, then return here.':'No careers found.'}</div>}</div><div className="panel why"><h3>Why these careers?</h3><p>Recommendations are stored from the platform recommendation service.</p><ul><li>✓ Academic programme</li><li>✓ Skills and verified evidence</li><li>✓ Career interests</li><li>✓ Assessment results</li></ul><div className="ai-note">✦ Recommendations are decision-support and are not guarantees of career outcomes.</div></div></div>}</div>;
}
