import React, { useEffect, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';

export default function JobEditor({ jobId }){
  const { token } = useAuth();
  const [loading,setLoading]=useState(!!jobId); const [error,setError]=useState(null); const [form,setForm]=useState({ title:'', description:'', type:'Full-time', location:'', salary_min:'', salary_max:'', deadline:'', required_skills:[], preferred_skills:[], experience_requirement:'', responsibilities:'', qualifications:'' });
  useEffect(()=>{ if(!jobId) return; (async()=>{ setLoading(true); const r=await fetch('/api/jobs/'+jobId); const d=await r.json(); if(r.ok){ setForm({ title:d.title, description:d.description, type:d.type, location:d.location, salary_min:d.salary_min||'', salary_max:d.salary_max||'', deadline:d.deadline||'', required_skills:[], preferred_skills:[], experience_requirement:d.min_experience||'', responsibilities:d.responsibilities||'', qualifications:d.qualifications||'' }); } else setError(d.error); setLoading(false); })(); },[jobId]);
  const save=async (publish=false)=>{ try{ setError(null); const payload = { ...form, status: publish? 'published':'draft' }; const res = await fetch('/api/jobs'+(jobId?'/'+jobId:''), { method: jobId? 'PUT':'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${token}` }, body: JSON.stringify(payload) }); const j = await res.json(); if(!res.ok) throw new Error(j.error||'Save failed'); if(publish && !jobId){ /* if new and publish, call publish endpoint */ await fetch('/api/jobs/'+j.job.id+'/publish', { method:'POST', headers:{ Authorization:`Bearer ${token}` } }); } return true; }catch(e){ setError(e.message); return false; } };
  if(!token) return <div className="panel"><h3>Please log in</h3></div>;
  if(loading) return <div className="panel">Loading…</div>;
  return <div><PageHeader eyebrow="Jobs" title={jobId? 'Edit job':'Create job'} description="Create or update job postings."/><div className="panel form-grid"><label>Job title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Full-time</option><option>Part-time</option><option>Internship</option></select></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label><label>Salary min<input value={form.salary_min} onChange={e=>setForm({...form,salary_min:e.target.value})}/></label><label>Salary max<input value={form.salary_max} onChange={e=>setForm({...form,salary_max:e.target.value})}/></label><label>Experience requirement<input value={form.experience_requirement} onChange={e=>setForm({...form,experience_requirement:e.target.value})}/></label><label>Responsibilities<textarea value={form.responsibilities} onChange={e=>setForm({...form,responsibilities:e.target.value})}/></label><label>Qualifications<textarea value={form.qualifications} onChange={e=>setForm({...form,qualifications:e.target.value})}/></label><label>Required skills<input placeholder="Comma separated" value={form.required_skills.join(', ')} onChange={e=>setForm({...form,required_skills: e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><label>Preferred skills<input placeholder="Comma separated" value={form.preferred_skills.join(', ')} onChange={e=>setForm({...form,preferred_skills: e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><div className="form-actions"><Button onClick={()=>save(false)}>Save draft</Button><Button onClick={async ()=>{ const ok=await save(true); if(ok) window.location.hash='manage-jobs'; }}>Publish</Button></div>{error&&<div className="error">{error}</div>}</div></div>;
}
