import React, { useEffect, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import { supabase } from '../lib/supabaseClient';
import { readableSupabaseError } from '../lib/supabaseData';

export default function JobEditor({ jobId }){
  const { token } = useAuth();
  const [loading,setLoading]=useState(!!jobId); const [error,setError]=useState(null); const [form,setForm]=useState({ title:'', description:'', type:'Full-time', location:'', salary_min:'', salary_max:'', deadline:'', required_skills:[], preferred_skills:[], experience_requirement:'', responsibilities:'', qualifications:'' });
  useEffect(()=>{ if(!jobId) return; (async()=>{ setLoading(true); const { data, error:queryError }=await supabase.from('jobs').select('*').eq('id',jobId).maybeSingle(); if(queryError) setError(readableSupabaseError(queryError,'Unable to load job.')); else if(data) setForm({ title:data.title||'', description:data.description||'', type:data.employment_type||'full_time', location:data.location_text||'', salary_min:data.salary_min||'', salary_max:data.salary_max||'', deadline:data.application_deadline||'', required_skills:[], preferred_skills:[], experience_requirement:'', responsibilities:'', qualifications:'' }); setLoading(false); })(); },[jobId]);
  const save=async (publish=false)=>{ try{ setError(null); const { data:userData }=await supabase.auth.getUser(); const { data:employer, error:employerError }=await supabase.from('employer_profiles').select('id').eq('user_id',userData.user.id).maybeSingle(); if(employerError) throw employerError; if(!employer) throw new Error('Create your company profile before posting a job.'); const payload={ employer_id:employer.id,title:form.title,description:form.description,employment_type:form.type,location_text:form.location,salary_min:form.salary_min?Number(form.salary_min):null,salary_max:form.salary_max?Number(form.salary_max):null,application_deadline:form.deadline||null,status:publish?'published':'draft',published_at:publish?new Date().toISOString():null }; const result=jobId?await supabase.from('jobs').update(payload).eq('id',jobId).eq('employer_id',employer.id).select('id').single():await supabase.from('jobs').insert(payload).select('id').single(); if(result.error) throw result.error; const savedId=result.data.id; await supabase.from('job_skills').delete().eq('job_id',savedId); for(const name of [...form.required_skills,...form.preferred_skills]){ const {data:skill}=await supabase.from('skills').select('id').eq('name',name).maybeSingle(); if(skill) await supabase.from('job_skills').upsert({job_id:savedId,skill_id:skill.id,importance:form.required_skills.includes(name)?100:50}); } return true; }catch(e){ setError(readableSupabaseError(e,'Unable to save job.')); return false; } };
  if(!token) return <div className="panel"><h3>Please log in</h3></div>;
  if(loading) return <div className="panel">Loading…</div>;
  return <div><PageHeader eyebrow="Jobs" title={jobId? 'Edit job':'Create job'} description="Create or update job postings."/><div className="panel form-grid"><label>Job title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Full-time</option><option>Part-time</option><option>Internship</option></select></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label><label>Salary min<input value={form.salary_min} onChange={e=>setForm({...form,salary_min:e.target.value})}/></label><label>Salary max<input value={form.salary_max} onChange={e=>setForm({...form,salary_max:e.target.value})}/></label><label>Experience requirement<input value={form.experience_requirement} onChange={e=>setForm({...form,experience_requirement:e.target.value})}/></label><label>Responsibilities<textarea value={form.responsibilities} onChange={e=>setForm({...form,responsibilities:e.target.value})}/></label><label>Qualifications<textarea value={form.qualifications} onChange={e=>setForm({...form,qualifications:e.target.value})}/></label><label>Required skills<input placeholder="Comma separated" value={form.required_skills.join(', ')} onChange={e=>setForm({...form,required_skills: e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><label>Preferred skills<input placeholder="Comma separated" value={form.preferred_skills.join(', ')} onChange={e=>setForm({...form,preferred_skills: e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label><div className="form-actions"><Button onClick={()=>save(false)}>Save draft</Button><Button onClick={async ()=>{ const ok=await save(true); if(ok) window.location.hash='manage-jobs'; }}>Publish</Button></div>{error&&<div className="error">{error}</div>}</div></div>;
}
