import React, { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import Badge from '../components/Badge';
import { supabase } from '../lib/supabaseClient';
import { readableSupabaseError } from '../lib/supabaseData';

export default function LearningResources(){
  const [list,setList]=useState([]); const [skillFilter,setSkillFilter]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const [progress,setProgress]=useState({});
  const fetchList = async ()=>{ setLoading(true); setError(null); let query=supabase.from('learning_resources').select('id,title,description,provider,url,resource_type,duration_minutes,difficulty,learning_resource_skills(skill_id,skills(name))').eq('published',true).order('created_at',{ascending:false}); if(skillFilter.trim()) query=query.eq('learning_resource_skills.skill_id',skillFilter.trim()); const { data,error:queryError }=await query; if(queryError){setError(readableSupabaseError(queryError,'Unable to load resources.'));setLoading(false);return;} const {data:{user}}=await supabase.auth.getUser(); if(user){const {data:progressRows}=await supabase.from('user_learning_progress').select('resource_id,status,progress_percent').eq('user_id',user.id); setProgress(Object.fromEntries((progressRows||[]).map(row=>[row.resource_id,row])));} setList(data||[]); setLoading(false); };
  useEffect(()=>{ fetchList(); },[skillFilter]);
  const save = async (id,status='saved')=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.hash='login';return;} const nextProgress=status==='completed'?100:(progress[id]?.progress_percent||0); const {error:saveError}=await supabase.from('user_learning_progress').upsert({user_id:user.id,resource_id:id,status,progress_percent:nextProgress},{onConflict:'user_id,resource_id'}); if(saveError) setError(readableSupabaseError(saveError,'Unable to update learning progress.')); else setProgress(current=>({...current,[id]:{status,progress_percent:nextProgress}})); };
  return <div><PageHeader eyebrow="Resources" title="Learning resources" description="Recommended resources are based on your skills and career goals."/><div className="panel form-grid resource-filter"><label>Skill filter<input value={skillFilter} onChange={e=>setSkillFilter(e.target.value)} placeholder="Enter a skill ID"/></label><div className="form-actions"><Button variant="outline" onClick={fetchList}>Refresh</Button></div></div>{error&&<div className="panel error">{error}</div>}{loading?<div className="learning-grid"><div className="panel">Loading resources…</div></div>:list.length?<div className="learning-grid">{list.map(r=>{const current=progress[r.id]?.progress_percent||0; const skills=(r.learning_resource_skills||[]).map(item=>item.skills?.name).filter(Boolean); return <article key={r.id} className="learning-card"><div className="learning-top"><div className="course-icon">▤</div><Badge tone="soft">{r.difficulty||'All levels'}</Badge></div><h3>{r.title}</h3><p>{skills.length?skills.join(' · '):r.provider||'SkillBridge Learning'} · {r.resource_type.replace('_',' ')} · {r.duration_minutes?`${r.duration_minutes} min`:'Self-paced'}</p><p>{r.description||'Explore this learning resource to build practical skills.'}</p><div className="progress-label"><span>{current}% complete</span><span>{current===100?'Completed':current?'In progress':'Not started'}</span></div><div className="progress-bar"><i style={{width:`${current}%`}}></i></div><Button variant={current?'outline':'primary'} onClick={()=>r.url&&window.open(r.url,'_blank')}>{current?'Continue':'Open resource'}</Button><Button variant="outline" onClick={()=>save(r.id,current===100?'saved':'completed')}>{current===100?'Save again':'Mark completed'}</Button></article>})}</div>:<div className="panel empty">No learning resources found.</div>}</div>;
}
