import React, { useState, useEffect } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import { useAuth } from '../auth/AuthProvider';
import { supabase } from '../lib/supabaseClient';
import { readableSupabaseError } from '../lib/supabaseData';

export default function ProjectEditor({ id }){
  const { user } = useAuth();
  const [error,setError]=useState(null);
  const [form,setForm]=useState({ title:'', description:'', technologies:'', skills:[], images:[], url:'', github_url:'', completion_date:'', role:'', outcome:'', published:false });
  useEffect(()=>{ if(!id) return; (async ()=>{ const { data,error:queryError }=await supabase.from('portfolio_projects').select('*').eq('id',id).maybeSingle(); if(queryError) setError(readableSupabaseError(queryError,'Unable to load project.')); else if(data) setForm({title:data.title||'',description:data.description||'',technologies:(data.technologies||[]).join(', '),skills:[],images:[],url:data.project_url||'',github_url:data.github_url||'',completion_date:data.completion_date||'',role:data.role||'',outcome:data.outcome||'',published:data.is_published||false}); })(); },[id]);
  const save = async ()=>{
    let { data:portfolio,error:portfolioError }=await supabase.from('portfolios').select('id').eq('user_id',user.id).maybeSingle(); if(portfolioError) return setError(readableSupabaseError(portfolioError,'Unable to load portfolio.')); if(!portfolio){ const created=await supabase.from('portfolios').insert({user_id:user.id,title:'My Portfolio'}).select('id').single(); if(created.error) return setError(readableSupabaseError(created.error,'Unable to create portfolio.')); portfolio=created.data; } const payload={portfolio_id:portfolio.id,title:form.title,description:form.description,technologies:form.technologies.split(',').map(item=>item.trim()).filter(Boolean),project_url:form.url||null,github_url:form.github_url||null,completion_date:form.completion_date||null,role:form.role||null,outcome:form.outcome||null,is_published:form.published}; const result=id?await supabase.from('portfolio_projects').update(payload).eq('id',id).select('id').single():await supabase.from('portfolio_projects').insert(payload).select('id').single(); if(result.error) setError(readableSupabaseError(result.error,'Unable to save project.')); else window.location.hash='my-portfolio'; };
  return <div><PageHeader eyebrow="Portfolio" title={id? 'Edit project':'New project'} description="Add projects to showcase your work." /><div className="panel form-grid">{error&&<div className="error">{error}</div>}<label>Title<input value={form.title} onChange={e=>setForm({...form, title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form, description:e.target.value})}/></label><label>Technologies<input value={form.technologies} onChange={e=>setForm({...form, technologies:e.target.value})}/></label><label>Project URL<input value={form.url} onChange={e=>setForm({...form, url:e.target.value})}/></label><label>GitHub URL<input value={form.github_url} onChange={e=>setForm({...form, github_url:e.target.value})}/></label><label>Completion date<input type="date" value={form.completion_date} onChange={e=>setForm({...form, completion_date:e.target.value})}/></label><label>Role<input value={form.role} onChange={e=>setForm({...form, role:e.target.value})}/></label><label>Outcome<textarea value={form.outcome} onChange={e=>setForm({...form, outcome:e.target.value})}/></label><label>Published<input type="checkbox" checked={form.published} onChange={e=>setForm({...form, published:e.target.checked})}/></label><div className="form-actions"><Button onClick={save}>Save project</Button></div></div></div>;
}
