import React, { useState, useEffect } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';

export default function ProjectEditor({ id }){
  const [form,setForm]=useState({ title:'', description:'', technologies:'', skills:[], images:[], url:'', github_url:'', completion_date:'', role:'', outcome:'', published:false });
  useEffect(()=>{ if(!id) return; (async ()=>{ const r=await fetch('/api/portfolio/me', { headers:{ Authorization:`Bearer ${localStorage.getItem('sb_token')}` } }); const d=await r.json(); })(); },[id]);
  const save = async ()=>{
    const payload = { ...form, skills: form.skills }; const method = id ? 'PUT' : 'POST'; const url = id ? '/api/portfolio/'+id : '/api/portfolio'; const r = await fetch(url, { method, headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${localStorage.getItem('sb_token')}` }, body: JSON.stringify(payload) }); const d = await r.json(); if(!r.ok) return alert(d.error||'Failed'); alert('Saved'); window.location.hash='my-portfolio'; };
  return <div><PageHeader eyebrow="Portfolio" title={id? 'Edit project':'New project'} description="Add projects to showcase your work." /><div className="panel form-grid"><label>Title<input value={form.title} onChange={e=>setForm({...form, title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form, description:e.target.value})}/></label><label>Technologies<input value={form.technologies} onChange={e=>setForm({...form, technologies:e.target.value})}/></label><label>Project URL<input value={form.url} onChange={e=>setForm({...form, url:e.target.value})}/></label><label>GitHub URL<input value={form.github_url} onChange={e=>setForm({...form, github_url:e.target.value})}/></label><label>Completion date<input type="date" value={form.completion_date} onChange={e=>setForm({...form, completion_date:e.target.value})}/></label><label>Role<input value={form.role} onChange={e=>setForm({...form, role:e.target.value})}/></label><label>Outcome<textarea value={form.outcome} onChange={e=>setForm({...form, outcome:e.target.value})}/></label><label>Published<input type="checkbox" checked={form.published} onChange={e=>setForm({...form, published:e.target.checked})}/></label><div className="form-actions"><Button onClick={save}>Save project</Button></div></div></div>;
}
