import React, { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import { supabase } from '../lib/supabaseClient';
import { readableSupabaseError } from '../lib/supabaseData';

export default function SkillGap(){
  const [careers,setCareers]=useState([]); const [careerId,setCareerId]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false);
  const [error,setError]=useState(null);
  useEffect(()=>{ (async ()=>{ const {data,error:queryError}=await supabase.from('careers').select('id,title').eq('active',true).order('title'); if(queryError) setError(readableSupabaseError(queryError,'Unable to load careers.')); else setCareers(data||[]); })(); },[]);
  const run = async ()=>{ if(!careerId) return alert('Choose career'); setLoading(true); setError(null); try{ const {data:{user}}=await supabase.auth.getUser(); const [{data:careerSkills,error:careerError},{data:userSkills,error:userError}]=await Promise.all([supabase.from('career_skills').select('skill_id,required_level,required_score,importance,skills(id,name)').eq('career_id',careerId),supabase.from('user_skills').select('skill_id,proficiency_level,proficiency_score,verified,skills(name)').eq('user_id',user.id)]); if(careerError||userError) throw careerError||userError; const scoreMap={beginner:25,intermediate:50,advanced:75,expert:100}; const existing=new Map((userSkills||[]).map(item=>[item.skill_id,item.proficiency_score ?? scoreMap[item.proficiency_level] ?? 0])); const items=(careerSkills||[]).map(item=>{const current=existing.get(item.skill_id)||0; const required=item.required_score ?? scoreMap[item.required_level] ?? 50; return {...item,current_score:current,required_score:required,gap_score:Math.max(required-current,0),priority:item.importance||50};}); const overall=items.length?Math.round(items.reduce((sum,item)=>sum+Math.min(item.current_score/item.required_score,1)*100,0)/items.length):0; const {data:analysis,error:analysisError}=await supabase.from('skills_gap_analyses').insert({user_id:user.id,target_career_id:careerId,overall_score:overall,generated_by:'rule_based_comparison'}).select('id').single(); if(analysisError) throw analysisError; const {error:itemError}=await supabase.from('skills_gap_items').insert(items.map(item=>({analysis_id:analysis.id,skill_id:item.skill_id,current_score:item.current_score,required_score:item.required_score,priority:item.priority,recommendation:item.gap_score?'Develop this skill through relevant learning resources.':'Maintain this skill.'}))); if(itemError) throw itemError; setResult({readiness_percent:overall,counts:{matched:items.filter(item=>item.gap_score===0).length,partial:items.filter(item=>item.gap_score>0&&item.current_score>0).length,missing:items.filter(item=>item.current_score===0).length},matched:items.filter(item=>item.gap_score===0).map(item=>({skill_id:item.skill_id,skill_name:item.skills.name})),partially_matched:items.filter(item=>item.gap_score>0&&item.current_score>0).map(item=>({skill_id:item.skill_id,skill_name:item.skills.name})),missing:items.filter(item=>item.current_score===0).map(item=>({skill_id:item.skill_id,skill_name:item.skills.name})),details:items.map(item=>({skill_id:item.skill_id,skill_name:item.skills.name,required_level:item.required_level||item.required_score,declared_proficiency:item.current_score,verified:false,assessment_percent:null,assessment_mapped:null,effective_proficiency:item.current_score,notes:[`Gap: ${item.gap_score}%`]}))}); }catch(queryError){setError(readableSupabaseError(queryError,'Unable to run skills-gap analysis.'));} finally{setLoading(false);} };
  return <div><PageHeader eyebrow="Skills Gap" title="Career skill-gap analysis" description="Compare your skills and assessments against a career's requirements." /><div className="panel form-grid"><label>Career<select value={careerId} onChange={e=>setCareerId(e.target.value)}><option value="">--select--</option>{careers.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div className="form-actions"><Button onClick={run}>{loading? 'Running…':'Run analysis'}</Button></div>{error&&<div className="error">{error}</div>}</div>{result && <div className="panel"><h3>Readiness: {result.readiness_percent}%</h3><p>Matched: {result.counts.matched} · Partial: {result.counts.partial} · Missing: {result.counts.missing}</p><h4>Matched Skills</h4><ul>{result.matched.map(m=><li key={m.skill_id}>{m.skill_name}</li>)}</ul><h4>Partially Matched</h4><ul>{result.partially_matched.map(m=><li key={m.skill_id}>{m.skill_name}</li>)}</ul><h4>Missing Skills</h4><ul>{result.missing.map(m=><li key={m.skill_id}>{m.skill_name}</li>)}</ul><h4>Details</h4>{result.details.map(d=> <div key={d.skill_id} className="detail"><b>{d.skill_name}</b><div>Required: {d.required_level}</div><div>Current: {d.declared_proficiency}</div><div>{d.notes.join(' · ')}</div></div>)}</div>}</div>;
}
