import React, { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';

export default function SkillGap(){
  const [careers,setCareers]=useState([]); const [careerId,setCareerId]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false);
  useEffect(()=>{ (async ()=>{ const r=await fetch('/api/careers'); const d=await r.json(); if(r.ok) setCareers(d); })(); },[]);
  const run = async ()=>{ if(!careerId) return alert('Choose career'); setLoading(true); const r=await fetch('/api/skills-gap/'+careerId, { headers: { Authorization: `Bearer ${localStorage.getItem('sb_token')}` } }); const d=await r.json(); setResult(d); setLoading(false); };
  return <div><PageHeader eyebrow="Skills Gap" title="Career skill-gap analysis" description="Compare your skills and assessments against a career's requirements." /><div className="panel form-grid"><label>Career<select value={careerId} onChange={e=>setCareerId(e.target.value)}><option value="">--select--</option>{careers.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div className="form-actions"><Button onClick={run}>{loading? 'Running…':'Run analysis'}</Button></div></div>{result && <div className="panel"><h3>Readiness: {result.readiness_percent}%</h3><p>Matched: {result.counts.matched} · Partial: {result.counts.partial} · Missing: {result.counts.missing}</p><h4>Matched Skills</h4><ul>{result.matched.map(m=><li key={m.skill_id}>{m.skill_name}</li>)}</ul><h4>Partially Matched</h4><ul>{result.partially_matched.map(m=><li key={m.skill_id}>{m.skill_name}</li>)}</ul><h4>Missing (with learning resources)</h4><ul>{result.missing.map(m=><li key={m.skill_id}>{m.skill_name}{m.resources && m.resources.length? <ul>{m.resources.map(r=> <li key={r.id}><a href={r.url} target="_blank" rel="noreferrer">{r.title}</a> — {r.provider}</li>)}</ul> : <small> — no resources</small>}</li>)}</ul><h4>Details</h4>{result.details.map(d=> <div key={d.skill_id} className="detail"><b>{d.skill_name}</b><div>Required level: {d.required_level}</div><div>Declared: {d.declared_proficiency}{d.verified? ' (verified)':''}</div><div>Assessment: {d.assessment_percent!==null? d.assessment_percent+'% (mapped '+d.assessment_mapped+')':'N/A'}</div><div>Effective: {d.effective_proficiency}</div><div>Notes: {d.notes.join(' · ')}</div></div>)}</div>}</div>;
}
