import React, { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import { supabase } from '../lib/supabaseClient';
import { readableSupabaseError } from '../lib/supabaseData';

export default function TakeAssessment({ id }){
  const [assessment,setAssessment]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(null);
  const [attemptId,setAttemptId]=useState(null); const [answers,setAnswers]=useState({}); const [current,setCurrent]=useState(0); const [submitting,setSubmitting]=useState(false); const [result,setResult]=useState(null);
  useEffect(()=>{ if(!id) return; (async ()=>{ setLoading(true); const {data,error:queryError}=await supabase.from('assessments').select('id,title,description,assessment_categories(name),assessment_questions(id,question_text,question_type,points,position,question_options(id,option_text))').eq('id',id).maybeSingle(); if(queryError) setError(readableSupabaseError(queryError,'Unable to load assessment.')); else if(data) setAssessment({assessment:{...data,category:data.assessment_categories?.name},questions:(data.assessment_questions||[]).sort((a,b)=>a.position-b.position).map(q=>({...q,text:q.question_text,options:(q.question_options||[]).map(o=>({...o,text:o.option_text}))}))}); setLoading(false); })(); },[id]);
  const start = async ()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.hash='login';return;} const {count}=await supabase.from('assessment_attempts').select('id',{count:'exact',head:true}).eq('assessment_id',id).eq('user_id',user.id); const {data,error}=await supabase.from('assessment_attempts').insert({assessment_id:id,user_id:user.id,attempt_number:(count||0)+1}).select('id').single(); if(error) setError(readableSupabaseError(error,'Unable to start assessment.')); else setAttemptId(data.id); };
  const setOption = (qid, oid)=>{ setAnswers(a=>({ ...a, [qid]: oid })); };
  const submit = async ()=>{ if(!attemptId) return; setSubmitting(true); try{ const optionIds=Object.values(answers); const {data:options,error:optionsError}=await supabase.from('question_options').select('id,question_id,is_correct').in('id',optionIds); if(optionsError) throw optionsError; const correctByQuestion=new Map((options||[]).map(option=>[option.question_id,option])); const answerRows=Object.entries(answers).map(([question_id,selected_option_id])=>({attempt_id:attemptId,question_id,selected_option_id,is_correct:correctByQuestion.get(question_id)?.is_correct||false,points_awarded:correctByQuestion.get(question_id)?.is_correct?(qs.find(q=>q.id===question_id)?.points||1):0})); const {error:answerError}=await supabase.from('assessment_answers').upsert(answerRows,{onConflict:'attempt_id,question_id'}); if(answerError) throw answerError; const correctCount=answerRows.filter(answer=>answer.is_correct).length; const scorePercent=qs.length?correctCount/qs.length*100:0; const {data:{user}}=await supabase.auth.getUser(); const {error:attemptError}=await supabase.from('assessment_attempts').update({status:'graded',submitted_at:new Date().toISOString(),completed_at:new Date().toISOString(),score:scorePercent}).eq('id',attemptId).eq('user_id',user.id); if(attemptError) throw attemptError; const {error:resultError}=await supabase.from('assessment_results').insert({attempt_id:attemptId,user_id:user.id,score:scorePercent,passed:scorePercent>=(assessment.assessment.passing_score||0)}); if(resultError) throw resultError; setResult({scorePercent,correctCount,totalQuestions:qs.length,skillScores:{}}); }catch(submitError){setError(readableSupabaseError(submitError,'Unable to submit assessment.'));} finally{setSubmitting(false);} };
  if(loading) return <div className="panel">Loading…</div>;
  if(error) return <div className="panel"><div className="error">{error}</div></div>;
  const qs = assessment.questions;
  const q = qs[current];
  return <div><PageHeader eyebrow="Assessment" title={assessment.assessment.title} description={assessment.assessment.category} /><div className="panel">{attemptId? <div className="attempt-info">Attempt: {attemptId}</div> : <Button onClick={start}>Start assessment</Button>} {q && <div className="question-card"><h3>Q{current+1}. {q.text}</h3>{q.options.map(o=><div key={o.id}><label><input type="radio" name={q.id} checked={answers[q.id]===o.id} onChange={()=>setOption(q.id,o.id)}/> {o.text}</label></div>)}<div className="question-actions"><Button variant="outline" onClick={()=>setCurrent(Math.max(0,current-1))}>Previous</Button>{current<qs.length-1? <Button onClick={()=>setCurrent(current+1)}>Next</Button> : <Button onClick={submit}>{submitting? 'Submitting…':'Submit assessment'}</Button> }</div></div> }</div>{result && <div className="panel"><h3>Result</h3><p>Score: {result.scorePercent.toFixed(2)}%</p><p>Correct: {result.correctCount} / {result.totalQuestions}</p><div><h4>Skill breakdown</h4>{Object.entries(result.skillScores).map(([skill,stats])=> <div key={skill}><b>{skill}</b><div>{stats.correct}/{stats.total} → {((stats.correct/stats.total)*100).toFixed(1)}%</div></div>)}</div></div>}</div>;
}
